# Generated by Django 4.2 on 2023-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_producto_categoria_producto_fechagregado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('numerotelefono', models.PositiveIntegerField()),
                ('contraseña', models.CharField(max_length=100)),
                ('confirmarcontraseña', models.CharField(max_length=100)),
                ('numerotarjeta', models.PositiveIntegerField()),
                ('fechavencimiento', models.DateField()),
                ('cvv', models.PositiveIntegerField()),
            ],
        ),
    ]
