# Generated by Django 4.2 on 2023-06-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_suscriptores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptores',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='suscriptores',
            name='fechavencimiento',
        ),
        migrations.RemoveField(
            model_name='suscriptores',
            name='numerotarjeta',
        ),
    ]
