# Generated by Django 4.2 on 2023-06-09 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_suscriptores_cvv_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCarrito',
            new_name='ProductoCarrito',
        ),
    ]
